#define ECC_VERSION_MAJOR 1
#define ECC_VERSION_MINOR 2
#define ECC_VERSION_PATCH 2
#define _ECC_STR(x) #x
#define ECC_STR(x) _ECC_STR(x)
#define CHIMERA_CORE_VERSION ECC_STR(ECC_VERSION_MAJOR) "." ECC_STR(ECC_VERSION_MINOR) "." ECC_STR(ECC_VERSION_PATCH_

