name: PlatformIOBuild

env:
  PROJECT_DIR: examples/Tests/build_test

on:
  push:
    paths:
    - '**.ino'
    - '**.cpp'
    - '**.hpp'
    - '**.h'
    - '**.c'
    - '**PlatformioBuild.yml'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.pio-env }}

    runs-on: ubuntu-latest

    strategy:
      matrix:

        pio-env:

          - esp32@1.0.6
          - esp32@2.0.1
          - esp32@2.0.2
          - esp32@2.0.3-RC1

          - m5stick-c@1.0.6
          - m5stick-c@2.0.1
          - m5stick-c@2.0.2
          - m5stick-c@2.0.3-RC1

          - m5stack-core-esp32@1.0.6
          - m5stack-core-esp32@2.0.1
          - m5stack-core-esp32@2.0.2
          - m5stack-core-esp32@2.0.3-RC1

          - m5stack-fire@1.0.6
          - m5stack-fire@2.0.1
          - m5stack-fire@2.0.2
          - m5stack-fire@2.0.3-RC1

          - m5stack-core2@1.0.6
          - m5stack-core2@2.0.1
          - m5stack-core2@2.0.2
          - m5stack-core2@2.0.3-RC1

          - odroid_esp32@1.0.6
          - odroid_esp32@2.0.1
          - odroid_esp32@2.0.2
          - odroid_esp32@2.0.3-RC1

          - esp-wrover-kit@1.0.6
          - esp-wrover-kit@2.0.1
          - esp-wrover-kit@2.0.2
          - esp-wrover-kit@2.0.3-RC1

          - esp32s3box@2.0.3-RC1

          - lolin_d32_pro@1.0.6
          - lolin_d32_pro@2.0.1
          - lolin_d32_pro@2.0.2
          - lolin_d32_pro@2.0.3-RC1

          - ttgo-t-watch@1.0.6
          - ttgo-t-watch@2.0.1
          - ttgo-t-watch@2.0.2
          - ttgo-t-watch@2.0.3-RC1

          - ttgo-t1@1.0.6
          - ttgo-t1@2.0.1
          - ttgo-t1@2.0.2
          - ttgo-t1@2.0.3-RC1

      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          pio lib install https://github.com/Lovyan03/LovyanGFX.git#develop
#      - name: Deploy dev dependencies
#        if branch != master:
#        run: |


      - name: Run PlatformIO
        run: |
          mkdir -p /tmp/piolib
          cp -R ../ESP32-Chimera-Core /tmp/piolib/
          cd ${{ env.PROJECT_DIR }} && pio run -e ${{ matrix.pio-env }}
