name: PlatformIOBuild

env:
  PROJECT_DIR: examples/Tests/build_test

on:
  push:
    paths:
    - '**.ino'
    - '**.cpp'
    - '**.hpp'
    - '**.h'
    - '**.c'
    - '**PlatformioBuild.yml'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.board }}@${{ matrix.platform-version }}

    runs-on: ubuntu-latest

    strategy:
      matrix:

        # this matrix must match the env names in platformio.ini
        # env names are like [board-name]@[arduino-esp32 version]
        platform-version:
          - 1.0.6
          - 2.0.1
          - 2.0.2
          - 2.0.3-RC1

        board:
          - esp32
          - m5stick-c
          - m5stack-core-esp32
          - m5stack-fire
          - m5stack-core2
          - odroid_esp32
          - esp-wrover-kit
          - esp32s3box
          - lolin_d32_pro
          - ttgo-t-watch
          - ttgo-t1

        exclude:
          - boards: esp32s3box
            platform-version: 1.0.6
          - boards: esp32s3box
            platform-version: 2.0.1
          - boards: esp32s3box
            platform-version: 2.0.2

        include:
          platform-version:
            - 1.0.6
            - 2.0.1
            - 2.0.2
            - 2.0.3-RC1
          board:
            - esp32
            - m5stick-c
            - m5stack-core-esp32
            - m5stack-fire
            - m5stack-core2
            - odroid_esp32
            - esp-wrover-kit
            - esp32s3box
            - lolin_d32_pro
            - ttgo-t-watch
            - ttgo-t1

      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          pio lib install https://github.com/Lovyan03/LovyanGFX.git#develop
#      - name: Deploy dev dependencies
#        if branch != master:
#        run: |


      - name: Run PlatformIO
        run: |
          mkdir -p /tmp/piolib
          cp -R ../ESP32-Chimera-Core /tmp/piolib/
#          cd ${{ env.PROJECT_DIR }} && pio run -e ${{ matrix.pio-env }}
          cd ${{ env.PROJECT_DIR }} && pio run -e ${{ matrix.board }}@${{ matrix.platform-version }}
